### ISSUE TITLE
Requesting the same test multiple times leads to assertion error

### ISSUE THREAD

**Issue by bbannier** [zeek/btest#69]
I was generating the tests to run from a script and ran into a failure when the same test appeared multiple times, e.g., in the BTest test suite:

```.console
$ btest tests.xml tests.xml
Traceback (most recent call last):
  File "/Users/bbannier/.local/bin/btest", line 2815, in <module>
    tests = mergeTestParts(tests)
  File "/Users/bbannier/.local/bin/btest", line 2195, in mergeTestParts
    assert t.part != other.part
AssertionError
```

It would be nice if BTest could deduplicate the list of tests for users.

**Comment by bbannier** [comment]
This was fixed by #71.
