### ISSUE TITLE
Running -d with non-utf8 encoded characters in output hangs process

### ISSUE THREAD

**Issue by awelzel** [zeek/btest#88]
Non UTF-8 encoded byte sequences in the .diag / stderr output hang btest when run with `-d`.

We ran into this in the following Cirrus CI build, where the Alpine job hung due to Zeek outputting non-UTF8 encoded bytes on stderr.
https://cirrus-ci.com/task/6325848790269952?logs=test#L24

The below test triggers the hang on Debian and also Alpine. I'm a bit uncertain why the Zeek CI run above only hung on Alpine, but might have been a baseline difference only there (and the difference then being displayed).

There seem to be two things: We should probably ignore decoding errors by some `errors=` strategy. The fact that the process hangs upon and unhandled Exception is a separate scary thing.

```
$ cat x.test
@TEST-EXEC: bash -c 'echo -e "\xed\xee\xef" >&2 && false'

$ btest -d x.test 
[  0%] x ... failed
  % 'bash -c 'echo -e "\xed\xee\xef" >&2 && false'' failed unexpectedly (exit code 1)
  % cat .stderr
Process #1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/awelzel/corelight-oss/zeek/auxil/btest/btest", line 500, in <lambda>
    name="#%d" % (i + 1), target=lambda: self.threadRun(i, mgr_data)
  File "/home/awelzel/corelight-oss/zeek/auxil/btest/btest", line 578, in threadRun
    t.run(self)
  File "/home/awelzel/corelight-oss/zeek/auxil/btest/btest", line 1337, in run
    run_cmdseq(seq)
  File "/home/awelzel/corelight-oss/zeek/auxil/btest/btest", line 1285, in run_cmdseq
    need_teardown |= run_cmdseq(cmd)
  File "/home/awelzel/corelight-oss/zeek/auxil/btest/btest", line 1307, in run_cmdseq
    self.mgr.testFailed(self)
  File "/home/awelzel/corelight-oss/zeek/auxil/btest/btest", line 765, in testFailed
    self._output_handler.testFailed(test, msg)
  File "/home/awelzel/corelight-oss/zeek/auxil/btest/btest", line 1716, in testFailed
    h.testFailed(test, msg)
  File "/home/awelzel/corelight-oss/zeek/auxil/btest/btest", line 2058, in testFailed
    self.showDiag(test)
  File "/home/awelzel/corelight-oss/zeek/auxil/btest/btest", line 2032, in showDiag
    for line in open(f):
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte

< ... hangs ... >
```

**Comment by awelzel** [comment]
Ah, so the hanging is because there's a thread stared running `monitor_cb()` and an unhandled exception results in the Process never dying until that thread has ended. Starting that with daemon=True seems reasonable to prevent hangs for unhandled exception within the processes.

**Comment by awelzel** [comment]
Ah, and the encoding issue is the fact that that `self.stdout = open(".stdout", "a", encoding="utf-8")` doesn't do what might have been expected. We can not control the encoding of the bytes a subprocess produces directly to the file descriptor, so instead we should be more careful when reading the output they produce.
